name: Funkin-Moon Build

"on":
push:
pull_request:
workflow_dispatch:

jobs:
android:
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4
    with:
      submodules: recursive

  - uses: krdlab/setup-haxe@v2
    with:
      haxe-version: 4.3.7

  - name: Install Dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y libvlc-dev libvlccore-dev
      haxelib install hmm
      haxelib --global run hmm install

  - name: Setup Android
    uses: android-actions/setup-android@v3

  - name: Install NDK
    run: sdkmanager "ndk;27.2.12479018"

  - name: Setup Haxe
    run: |
      echo "HAXEPATH=$(haxelib config)" >> "$GITHUB_ENV"
      haxelib --always run lime setup

  - name: Build Android
    run: haxelib run lime build android -release

  - name: Upload APK
    uses: actions/upload-artifact@v4
    with:
      name: Funkin-Moon-Android
      path: export/android/**/*.apk

windows:
runs-on: windows-latest

steps:
  - uses: actions/checkout@v4
    with:
      submodules: recursive

  - uses: krdlab/setup-haxe@v2
    with:
      haxe-version: 4.3.7

  - name: Install Dependencies
    shell: pwsh
    run: |
      haxelib install hmm
      haxelib --global run hmm install

  - name: Setup Haxe
    shell: pwsh
    run: |
      "HAXEPATH=$(haxelib config)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      haxelib --always run lime setup

  - name: Build Windows
    shell: pwsh
    run: haxelib run lime build windows -release

  - name: Upload Windows
    uses: actions/upload-artifact@v4
    with:
      name: Funkin-Moon-Windows
      path: export/windows/**
